name: CI
run-name: CI on ${{ github.event_name }}

on:
  push:
    branches:
      - 'ci'
    paths:
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: package
        run: echo "build artifact"

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Run tests"
          exit 1
