name: Code Quality
run-name: ${{ github.ref }} to ${{ github.ref_name }} branch - testing2

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - releases/**
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Run tests"