name: CRUD operations
run-name: running crud on branch - ${{ github.event.ref }}

on:
  create: {}
  delete: {}
  push:
    branches:
      - 'main'
      - 'dev/**'
    paths:
      - 'src/**'
      - '.github/workflows/crud.yml'

jobs:
  basic:
    runs-on: ubuntu-latest

    steps:
      - run: echo "basic - github.ref > ${{ github.ref }}, github.event.ref > ${{ github.event.ref }}"

  if:
    if: ${{ contains(github.ref, 'refs/heads/dev/') }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "if - github.ref > ${{ github.ref }}, github.event.ref > ${{ github.event.ref }}"