name: Build and Deployment
run-name: ${{ github.actor }} running on ${{ github.ref_name }} branch
on: push
jobs:
  build:
    uses: nikhileshtippana/devops/.github/workflows/java.yml@main
    with:
      java-version: '8'