name: Sync Ops
run-name: ${{ github.event.ref }} branch on ${{ github.event_name }}

on:
  create: {}
  delete: {}
  push:
    branches:
      - 'main'
      - 'dev/**'
    paths:
      - 'src/**'
      - '.github/workflows/sync_ops.yml'

jobs:
  sync:
    if: ${{ contains(fromJSON('["create", "push"]'), github.event_name) && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev/') ) }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "dir_path=${{ vars.SYNC_MAIN_PATH }}" >> "$GITHUB_ENV"
          else
            DIR_PATH=${{ vars.SYNC_DEV_PATH_PREFIX }}-$(echo "${{ github.ref }}" | sed 's/refs\/heads\/dev\///' | sed 's/\//_/')
            echo "dir_path=$DIR_PATH" >> "$GITHUB_ENV"
          fi

      - name: Sync branch to a path on server
        run: echo "Sync to ${{ vars.SYNC_SERVER_NAME }} @ $dir_path"

  cleanup:
    if: ${{ github.event_name == 'delete' && startsWith(github.event.ref, 'dev/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup branch related path on server
        run: echo "Cleanup ${{ github.event.ref }}"